UPDATE PRODUCT SET STATUS = 'ACT' WHERE STATUS = 'A';
UPDATE PRODUCT SET STATUS = 'INA' WHERE STATUS = 'I';

UPDATE PRODUCT_DETAIL SET STATUS = 'ACT' WHERE STATUS = 'A';
UPDATE PRODUCT_DETAIL SET STATUS = 'INA' WHERE STATUS = 'I';