INSERT INTO SYS_ACCOUNT(USERNAME, PASSWORD, HO_TEN, GIOI_TINH, ROLE, TRANG_THAI) VALUES('admin', '$2a$12$UGPx1eE9SzfvCDniYtwoZuQRzVdjHKkjbZcDKXO4.1Z/uGpOsFFVu', 'Quản trị hệ thống', 1, 'ADMIN', 1)

INSERT INTO SYS_CONFIG(CODE, NAME, VALUE, SORT) VALUES('EMAIL_HOST', 'Email host', 'smtp', 0);
INSERT INTO SYS_CONFIG(CODE, NAME, VALUE, SORT) VALUES('EMAIL_PORT', 'Email port', '587', 0);
INSERT INTO SYS_CONFIG(CODE, NAME, VALUE, SORT) VALUES('EMAIL_USERNAME', 'Email username', null, 0);
INSERT INTO SYS_CONFIG(CODE, NAME, VALUE, SORT) VALUES('EMAIL_PASSWORD', 'Email password', null, 0);
INSERT INTO SYS_CONFIG(CODE, NAME, VALUE, SORT) VALUES('TIMEOUT', 'Thời gian timeout', null, 0);
INSERT INTO SYS_CONFIG(CODE, NAME, VALUE, SORT) VALUES('PATH_UPLOAD', 'Thư mục lưu file upload', null, 0);
INSERT INTO SYS_CONFIG(CODE, NAME, VALUE, SORT) VALUES('SEND_MAIL_REPORT_DAILY', 'Gửi mail báo cáo hoạt động kinh doanh hàng ngày', null, 0);
INSERT INTO SYS_CONFIG(CODE, NAME, VALUE, SORT) VALUES('MAX_SIZE_UPLOAD', 'Dung lượng file tối đa cho phép upload', null, 0);
INSERT INTO SYS_CONFIG(CODE, NAME, VALUE, SORT) VALUES('EXTENSION_ALLOWED_UPLOAD', 'Định dạng file được phép upload', null, 0);

INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('UNIT', 'ROOT', 'Đơn vị tính', 0, 0, '/system/category/unit');
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('UNIT', null, 'Cái', 0, 0, null);
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('UNIT', null, 'Cuộn', 0, 0, null);
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('UNIT', null, 'Mét', 0, 0, null);
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('UNIT', null, 'Cộng', 0, 0, null);

INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('PAYMETHOD', 'ROOT', 'Hình thức thanh toán', 0, 0, '/system/category/pay-method');
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('PAYMETHOD', null, 'Chuyển khoản', 0, 0, null);
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('PAYMETHOD', null, 'Tiền mặt', 0, 0, null);
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('PAYMETHOD', null, 'Ghi sổ', 0, 0, null);

INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('FABRICTYPE', 'ROOT', 'Chất liệu vải', 0, 0, '/system/category/fabric-type');
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('FABRICTYPE', null, 'Kaki', 0, 0, null);
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('FABRICTYPE', null, 'Jean', 0, 0, null);
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('FABRICTYPE', null, 'Kate', 0, 0, null);
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('FABRICTYPE', null, 'Voan', 0, 0, null);
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('FABRICTYPE', null, 'Cotton', 0, 0, null);

INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('SALESCHANNEL', 'ROOT', 'Kênh bán hàng', 0, 0, '/system/category/sales-channel');
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('SALESCHANNEL', null, 'Shopee', 0, 0, null);
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('SALESCHANNEL', null, 'Instagram', 0, 0, null);
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('SALESCHANNEL', null, 'Facebook', 0, 0, null);
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('SALESCHANNEL', null, 'Zalo', 0, 0, null);

INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('SIZE', 'ROOT', 'Kích cỡ', 0, 0, '/system/category/size');
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('SIZE', null, 'S', 0, 0, null);
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('SIZE', null, 'M', 0, 0, null);
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('SIZE', null, 'L', 0, 0, null);
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('SIZE', null, 'XL', 0, 0, null);

INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('COLOR', 'ROOT', 'Màu sắc', 0, 0, '/system/category/color');
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('COLOR', null, 'Trắng', 0, 0, null);
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('COLOR', null, 'Đen', 0, 0, null);
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('COLOR', null, 'Cam', 0, 0, null);
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('COLOR', null, 'Vàng', 0, 0, null);

INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('PRODUCTTYPE', 'ROOT', 'Loại sản phẩm', 0, 0, '/system/category/product-type');
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('PRODUCTTYPE', null, 'Áo thun', 0, 0, null);
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('PRODUCTTYPE', null, 'Áo sơ mi', 0, 0, null);
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('PRODUCTTYPE', null, 'Quần tây', 0, 0, null);
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('PRODUCTTYPE', null, 'Đầm', 0, 0, null);
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('PRODUCTTYPE', null, 'Váy', 0, 0, null);

INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('DOCUMENTTYPE', 'ROOT', 'Loại tài liệu', 0, 0, '/system/category/document-type');
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('DOCUMENTTYPE', null, 'Văn bản hành chính', 0, 0, null);

INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('ORDERSTATUS', 'ROOT', 'Trạng thái đơn hàng', 0, 0, '/system/category/order-status');
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('ORDERSTATUS', 'PR', 'Đang chuẩn bị đơn hàng', 0, 0, null);
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('ORDERSTATUS', 'WS', 'Đang chờ đơn vị vận chuyển tiếp nhận', 0, 0, null);
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('ORDERSTATUS', 'DE', 'Đang vận chuyển', 0, 0, null);
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('ORDERSTATUS', 'DO', 'Đã hoàn thành', 0, 0, null);

INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('PAYMENTSTATUS', 'ROOT', 'Trạng thái thanh toán', 0, 0, '/system/category/payment-status');
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('PAYMENTSTATUS', 'UNPAID', 'Chưa thanh toán', 0, 0, null);
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('PAYMENTSTATUS', 'PARTLY-PAID', 'Thanh toán một phần', 0, 0, null);
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('PAYMENTSTATUS', 'PAID', 'Đã thanh toán', 0, 0, null);

INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('BRAND', 'ROOT', 'Thương hiệu', 0, 0, '/system/category/brand');
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('BRAND', null, 'Flowiee', 0, 0, null);

INSERT INTO PRO_PRODUCT(TEN_SAN_PHAM, BRAND_ID, PRODUCT_TYPE_ID, UNIT_ID, STATUS) VALUES ('Áo sơ mi sọc tay dài', (SELECT ID FROM CATEGORY WHERE TYPE = 'BRAND' AND ROWNUM <= 1), (SELECT ID FROM CATEGORY WHERE TYPE = 'PRODUCTTYPE' AND ROWNUM <= 1), (SELECT ID FROM CATEGORY WHERE TYPE = 'UNIT' AND ROWNUM <= 1), 'A');
INSERT INTO PRO_PRODUCT(TEN_SAN_PHAM, BRAND_ID, PRODUCT_TYPE_ID, UNIT_ID, STATUS) VALUES ('Áo thun unisex', (SELECT ID FROM CATEGORY WHERE TYPE = 'BRAND' AND ROWNUM <= 1), (SELECT ID FROM CATEGORY WHERE TYPE = 'PRODUCTTYPE' AND ROWNUM <= 1), (SELECT ID FROM CATEGORY WHERE TYPE = 'UNIT' AND ROWNUM <= 1), 'A');
INSERT INTO PRO_PRODUCT(TEN_SAN_PHAM, BRAND_ID, PRODUCT_TYPE_ID, UNIT_ID, STATUS) VALUES ('Quần sọt', (SELECT ID FROM CATEGORY WHERE TYPE = 'BRAND' AND ROWNUM <= 1), (SELECT ID FROM CATEGORY WHERE TYPE = 'PRODUCTTYPE' AND ROWNUM <= 1), (SELECT ID FROM CATEGORY WHERE TYPE = 'UNIT' AND ROWNUM <= 1), 'A');
INSERT INTO PRO_PRODUCT(TEN_SAN_PHAM, BRAND_ID, PRODUCT_TYPE_ID, UNIT_ID, STATUS) VALUES ('Quần jean', (SELECT ID FROM CATEGORY WHERE TYPE = 'BRAND' AND ROWNUM <= 1), (SELECT ID FROM CATEGORY WHERE TYPE = 'PRODUCTTYPE' AND ROWNUM <= 1), (SELECT ID FROM CATEGORY WHERE TYPE = 'UNIT' AND ROWNUM <= 1), 'A');
INSERT INTO PRO_PRODUCT(TEN_SAN_PHAM, BRAND_ID, PRODUCT_TYPE_ID, UNIT_ID, STATUS) VALUES ('Áo khoác có nón', (SELECT ID FROM CATEGORY WHERE TYPE = 'BRAND' AND ROWNUM <= 1), (SELECT ID FROM CATEGORY WHERE TYPE = 'PRODUCTTYPE' AND ROWNUM <= 1), (SELECT ID FROM CATEGORY WHERE TYPE = 'UNIT' AND ROWNUM <= 1), 'A');

INSERT INTO PRO_CUSTOMER(TEN_KHACH_HANG, GIOI_TINH) VALUES ('Nguyễn Đức Việt', 1);
INSERT INTO PRO_CUSTOMER(TEN_KHACH_HANG, GIOI_TINH) VALUES ('Bùi Văn Tấn Đạt', 1);
INSERT INTO PRO_CUSTOMER(TEN_KHACH_HANG, GIOI_TINH) VALUES ('Nguyễn Thành Nam', 1);
INSERT INTO PRO_CUSTOMER(TEN_KHACH_HANG, GIOI_TINH) VALUES ('Nguyễn Hoàng Duy', 1);
INSERT INTO PRO_CUSTOMER(TEN_KHACH_HANG, GIOI_TINH) VALUES ('Nguyễn Chí Hải', 1);

INSERT INTO PRO_DON_HANG(MA_DON_HANG, THOI_GIAN_DAT_HANG, CUSTOMER_ID, KENH_BAN_HANG, NHAN_VIEN_BAN_HANG, TRANG_THAI_DON_HANG) VALUES('000', current_timestamp, (SELECT ID FROM PRO_CUSTOMER WHERE TEN_KHACH_HANG = 'Nguyễn Đức Việt' AND ROWNUM <= 1), (SELECT ID FROM CATEGORY WHERE TYPE = 'SALESCHANNEL' AND ROWNUM <= 1), (SELECT ID FROM SYS_ACCOUNT WHERE USERNAME = 'admin'), (SELECT ID FROM CATEGORY WHERE TYPE = 'ORDERSTATUS' AND ROWNUM <= 1));