INSERT INTO SYS_ACCOUNT(USERNAME, PASSWORD, HO_TEN, GIOI_TINH, ROLE, SO_DIEN_THOAI, TRANG_THAI) VALUES('admin', '$2a$12$UGPx1eE9SzfvCDniYtwoZuQRzVdjHKkjbZcDKXO4.1Z/uGpOsFFVu', 'Quản trị hệ thống', 1, '0706820684', 'ADMIN', 1);

INSERT INTO SYS_CONFIG(CODE, NAME, VALUE, SORT) VALUES('EMAIL_HOST', 'Email host', 'smtp', 0);
INSERT INTO SYS_CONFIG(CODE, NAME, VALUE, SORT) VALUES('EMAIL_PORT', 'Email port', '587', 0);
INSERT INTO SYS_CONFIG(CODE, NAME, VALUE, SORT) VALUES('EMAIL_USERNAME', 'Email username', null, 0);
INSERT INTO SYS_CONFIG(CODE, NAME, VALUE, SORT) VALUES('EMAIL_PASSWORD', 'Email password', null, 0);
INSERT INTO SYS_CONFIG(CODE, NAME, VALUE, SORT) VALUES('TIMEOUT', 'Thời gian timeout', null, 0);
INSERT INTO SYS_CONFIG(CODE, NAME, VALUE, SORT) VALUES('PATH_UPLOAD', 'Thư mục lưu file upload', null, 0);
INSERT INTO SYS_CONFIG(CODE, NAME, VALUE, SORT) VALUES('SEND_MAIL_REPORT_DAILY', 'Gửi mail báo cáo hoạt động kinh doanh hàng ngày', null, 0);
INSERT INTO SYS_CONFIG(CODE, NAME, VALUE, SORT) VALUES('MAX_SIZE_UPLOAD', 'Dung lượng file tối đa cho phép upload', null, 0);
INSERT INTO SYS_CONFIG(CODE, NAME, VALUE, SORT) VALUES('EXTENSION_ALLOWED_UPLOAD', 'Định dạng file được phép upload', null, 0);

INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('UNIT', 'ROOT', 'Đơn vị tính', 0, 0, '/system/category/unit');
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('UNIT', 'CA', 'Cái', 0, 0, null);
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('UNIT', 'CU', 'Cuộn', 0, 0, null);
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('UNIT', 'M', 'Mét', 0, 0, null);
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('UNIT', 'CO', 'Cộng', 0, 0, null);

INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('PAYMENT_METHOD', 'ROOT', 'Hình thức thanh toán', 0, 0, '/system/category/pay-method');
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('PAYMENT_METHOD', 'B', 'Chuyển khoản', 0, 0, null);
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('PAYMENT_METHOD', 'C', 'Tiền mặt', 0, 0, null);
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('PAYMENT_METHOD', 'D', 'Ghi sổ', 0, 0, null);

INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('FABRIC_TYPE', 'ROOT', 'Chất liệu vải', 0, 0, '/system/category/fabric-type');
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('FABRIC_TYPE', 'KK', 'Kaki', 0, 0, null);
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('FABRIC_TYPE', 'JE', 'Jean', 0, 0, null);
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('FABRIC_TYPE', 'KT', 'Kate', 0, 0, null);
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('FABRIC_TYPE', 'VO', 'Voan', 0, 0, null);
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('FABRIC_TYPE', 'CO', 'Cotton', 0, 0, null);

INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('SALES_CHANNEL', 'ROOT', 'Kênh bán hàng', 0, 0, '/system/category/sales-channel');
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('SALES_CHANNEL', 'SP', 'Shopee', 0, 0, null);
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('SALES_CHANNEL', 'IG', 'Instagram', 0, 0, null);
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('SALES_CHANNEL', 'FB', 'Facebook', 0, 0, null);
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('SALES_CHANNEL', 'ZL', 'Zalo', 0, 0, null);

INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('SIZE', 'ROOT', 'Kích cỡ', 0, 0, '/system/category/size');
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('SIZE', 'S', 'S', 0, 0, null);
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('SIZE', 'M', 'M', 0, 0, null);
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('SIZE', 'L', 'L', 0, 0, null);
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('SIZE', 'XL', 'XL', 0, 0, null);

INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('COLOR', 'ROOT', 'Màu sắc', 0, 0, '/system/category/color');
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('COLOR', 'WHITE', 'Trắng', 0, 0, null);
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('COLOR', 'BLACK', 'Đen', 0, 0, null);
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('COLOR', 'ORANGE', 'Cam', 0, 0, null);
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('COLOR', 'YELLOW', 'Vàng', 0, 0, null);

INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT, ICON) VALUES('PRODUCT_TYPE', 'ROOT', 'Loại sản phẩm', 0, 0, '/system/category/product-type', 'fa-solid fa-shirt');
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('PRODUCT_TYPE', 'AT', 'Áo thun', 0, 0, null);
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('PRODUCT_TYPE', 'ASM', 'Áo sơ mi', 0, 0, null);
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('PRODUCT_TYPE', 'QT', 'Quần tây', 0, 0, null);
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('PRODUCT_TYPE', 'D', 'Đầm', 0, 0, null);
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('PRODUCT_TYPE', 'V', 'Váy', 0, 0, null);

INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT, ICON) VALUES('DOCUMENT_TYPE', 'ROOT', 'Loại tài liệu', 0, 0, '/system/category/document-type', 'fa-solid fa-file-pdf');
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('DOCUMENT_TYPE', 'VBHC', 'Văn bản hành chính', 0, 0, null);

INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('ORDER_STATUS', 'ROOT', 'Trạng thái đơn hàng', 0, 0, '/system/category/order-status');
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('ORDER_STATUS', 'PR', 'Đang chuẩn bị đơn hàng', 0, 0, null);
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('ORDER_STATUS', 'WS', 'Đang chờ đơn vị vận chuyển tiếp nhận', 0, 0, null);
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('ORDER_STATUS', 'DE', 'Đang vận chuyển', 0, 0, null);
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('ORDER_STATUS', 'DO', 'Đã hoàn thành', 0, 0, null);

INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('PAYMENT_STATUS', 'ROOT', 'Trạng thái thanh toán', 0, 0, '/system/category/payment-status');
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('PAYMENT_STATUS', 'UNPAID', 'Chưa thanh toán', 0, 0, null);
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('PAYMENT_STATUS', 'PARTLY-PAID', 'Thanh toán một phần', 0, 0, null);
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('PAYMENT_STATUS', 'PAID', 'Đã thanh toán', 0, 0, null);

INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('BRAND', 'ROOT', 'Thương hiệu', 0, 0, '/system/category/brand');
INSERT INTO CATEGORY(TYPE, CODE, NAME, STATUS, IS_DEFAULT, ENDPOINT) VALUES('BRAND', 'FW', 'Flowiee', 0, 0, null);

INSERT INTO PRO_PRODUCT(TEN_SAN_PHAM, BRAND_ID, PRODUCT_TYPE_ID, UNIT_ID, STATUS) VALUES ('Áo sơ mi sọc tay dài', (SELECT ID FROM CATEGORY WHERE TYPE = 'BRAND' AND CODE = 'FW' AND ROWNUM <= 1), (SELECT ID FROM CATEGORY WHERE TYPE = 'PRODUCT_TYPE' AND CODE = 'AT' AND ROWNUM <= 1), (SELECT ID FROM CATEGORY WHERE TYPE = 'UNIT' AND CODE = 'CA' AND ROWNUM <= 1), 'ACTIVE');
INSERT INTO PRO_PRODUCT(TEN_SAN_PHAM, BRAND_ID, PRODUCT_TYPE_ID, UNIT_ID, STATUS) VALUES ('Áo thun unisex', (SELECT ID FROM CATEGORY WHERE TYPE = 'BRAND' AND CODE = 'FW' AND ROWNUM <= 1), (SELECT ID FROM CATEGORY WHERE TYPE = 'PRODUCT_TYPE' AND CODE = 'ASM' AND ROWNUM <= 1), (SELECT ID FROM CATEGORY WHERE TYPE = 'UNIT' AND CODE <> 'CO' AND ROWNUM <= 1), 'ACTIVE');
INSERT INTO PRO_PRODUCT(TEN_SAN_PHAM, BRAND_ID, PRODUCT_TYPE_ID, UNIT_ID, STATUS) VALUES ('Quần sọt', (SELECT ID FROM CATEGORY WHERE TYPE = 'BRAND' AND CODE = 'FW' AND ROWNUM <= 1), (SELECT ID FROM CATEGORY WHERE TYPE = 'PRODUCT_TYPE' AND CODE = 'QT' AND ROWNUM <= 1), (SELECT ID FROM CATEGORY WHERE TYPE = 'UNIT' AND CODE <> 'CU' AND ROWNUM <= 1), 'ACTIVE');
INSERT INTO PRO_PRODUCT(TEN_SAN_PHAM, BRAND_ID, PRODUCT_TYPE_ID, UNIT_ID, STATUS) VALUES ('Quần jean', (SELECT ID FROM CATEGORY WHERE TYPE = 'BRAND' AND CODE = 'FW' AND ROWNUM <= 1), (SELECT ID FROM CATEGORY WHERE TYPE = 'PRODUCT_TYPE' AND CODE = 'D' AND ROWNUM <= 1), (SELECT ID FROM CATEGORY WHERE TYPE = 'UNIT' AND CODE <> 'M' AND ROWNUM <= 1), 'ACTIVE');
INSERT INTO PRO_PRODUCT(TEN_SAN_PHAM, BRAND_ID, PRODUCT_TYPE_ID, UNIT_ID, STATUS) VALUES ('Áo khoác có nón', (SELECT ID FROM CATEGORY WHERE TYPE = 'BRAND' AND CODE = 'FW' AND ROWNUM <= 1), (SELECT ID FROM CATEGORY WHERE TYPE = 'PRODUCT_TYPE' AND CODE = 'V' AND ROWNUM <= 1), (SELECT ID FROM CATEGORY WHERE TYPE = 'UNIT' AND CODE <> 'CA' AND ROWNUM <= 1), 'ACTIVE');

INSERT INTO PRO_CUSTOMER(TEN_KHACH_HANG, BIRTHDAY, GIOI_TINH) VALUES ('Nguyễn Đức Việt', CURRENT_TIMESTAMP, 1);
INSERT INTO PRO_CUSTOMER(TEN_KHACH_HANG, BIRTHDAY, GIOI_TINH) VALUES ('Bùi Văn Tấn Đạt', CURRENT_TIMESTAMP, 1);
INSERT INTO PRO_CUSTOMER(TEN_KHACH_HANG, BIRTHDAY, GIOI_TINH) VALUES ('Nguyễn Thành Nam', CURRENT_TIMESTAMP, 1);
INSERT INTO PRO_CUSTOMER(TEN_KHACH_HANG, BIRTHDAY, GIOI_TINH) VALUES ('Nguyễn Hoàng Duy', CURRENT_TIMESTAMP, 1);
INSERT INTO PRO_CUSTOMER(TEN_KHACH_HANG, BIRTHDAY, GIOI_TINH) VALUES ('Nguyễn Chí Hải', CURRENT_TIMESTAMP, 1);

CREATE OR REPLACE VIEW PRO_VOUCHER_INFO_VIEW AS
SELECT v.*, (CASE WHEN ((TRUNC(START_TIME) <= TRUNC(CURRENT_DATE)) AND (TRUNC(END_TIME) >= TRUNC(CURRENT_DATE))) THEN 'ACTIVE' ELSE 'INACTIVE' END) AS STATUS FROM PRO_VOUCHER_INFO v;